# Generated by Django 2.0 on 2017-12-14 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadership', models.FloatField(default=0)),
                ('publicity', models.FloatField(default=0)),
                ('integrity', models.FloatField(default=0)),
                ('voters', models.IntegerField(default=0)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leader.Leader')),
            ],
        ),
    ]
